services:
  __APP_NAME__:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/__APP_NAME__:latest
    container_name: __APP_NAME__
    restart: unless-stopped
    working_dir: /app
    ports:
      - "${PORT}:${PORT_EXPOSED}"
    volumes:
      - "${MEDIA_DIR}:/mnt/media"
    environment:
      VIRTUAL_HOST: "${DOMAIN}"
      LETSENCRYPT_HOST: "${DOMAIN}"
      PUID: "${PUID}"
      PGID: "${PGID}"

networks:
  default:
    name: dockerweb
    external: true
