name: Deploy Nuxt App
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      volumes:
        - /var/docker-web:/var/docker-web

    steps:
      - uses: actions/checkout@v4
      - name: install
        run: |
          APP_DIR=/var/docker-web/apps/${GITHUB_REPOSITORY##*/}
          mkdir -p $APP_DIR
          cp -a $(find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name 'node_modules') "$APP_DIR/"
      - name: up
        run: |
          export COMPOSE_BAKE=false
          bash /var/docker-web/src/cli.sh up ${GITHUB_REPOSITORY##*/}
